#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[318] =
    {   0,
        0,    0,  102,  100,   99,   99,   87,  100,    1,   93,
       86,  100,   81,   82,   91,   90,   78,   89,   85,   92,
       43,   44,   79,   75,   94,   80,   95,   98,   41,   41,
       83,   84,   96,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   76,
       97,   77,   88,   74,    0,   52,    0,   60,   77,   69,
       61,    0,    0,   58,   66,   56,   67,   57,   68,    0,
       47,    2,    3,   59,   48,   43,    0,    0,   43,   43,
        0,   43,   44,   44,   44,   44,   84,   76,   83,   65,
       71,   73,   72,   64,   41,    0,    0,   62,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   13,   41,   41,
       41,   41,   41,   41,   21,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   63,   70,   45,   53,
        0,   47,    3,   47,    0,   48,    0,   46,   43,   43,
       43,   43,    0,   42,   44,   44,   44,   44,   55,   54,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   19,   41,   41,   24,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,    0,   47,    0,   47,    0,   48,
       46,   43,    0,    0,   42,    0,   42,   42,   44,   41,

       41,   41,    4,   41,    7,    8,   41,   41,   41,   41,
       15,   16,   41,   41,   20,   41,   25,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   38,
       41,   41,    0,   47,    0,    0,    0,   42,   42,    0,
       49,   42,   42,    5,   41,   41,    6,   10,   41,   41,
       41,   41,   18,   41,   41,   41,   41,   29,   41,   41,
       41,   41,   41,   41,   36,   41,   41,   40,    0,   50,
        0,    0,   51,   49,   42,   41,   41,   41,   41,   14,
       17,   23,   41,   41,   28,   30,   31,   32,   33,   34,
       41,   41,   41,   50,    0,   50,   51,   41,   41,   41,

       12,   41,   41,   35,   41,   41,   50,    9,   41,   11,
       26,   27,   37,   39,   41,   22,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   35,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    6,    6,    6,    7,    6,    6,    1,    1,    1,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    7,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[325] =
    {   0,
        0,    0,  542,  543,  543,  543,  517,   66,  543,   48,
       66,  501,  543,  543,  515,   62,  543,   63,   61,   72,
       90,   81,  513,  543,   95,  513,   58,  543,    0,   86,
      543,  543,  512,   65,  474,  476,   79,   29,   59,   51,
      477,   77,  476,  484,   89,  465,  474,  472,  477,  543,
       68,  543,  543,  543,  108,  543,    0,  543,  543,  543,
      543,   94,  517,  543,  543,  543,  543,  543,  543,  509,
      126,  543,    0,  543,  146,  151,  170,  188,  114,  119,
      508,  102,  195,  148,  125,  166,  543,  543,  543,  499,
      543,  543,  543,  498,    0,  153,  482,  543,  464,  463,

      464,  457,  469,  456,  471,  458,  464,  450,  451,  448,
      448,  451,  448,  445,    0,  108,  449,  161,  447,  156,
      175,  451,  444,  132,  144,  449,  543,  543,  543,  543,
      217,  543,    0,  220,  240,  543,  225,  243,  180,  543,
      465,  445,    0,  236,  188,  543,  463,  443,  543,  543,
      439,  440,  450,  436,  448,  443,  431,   71,  445,  443,
      439,  431,  437,  440,    0,  426,  430,    0,  431,  428,
      418,  416,  418,  420,  427,  413,  411,  411,  423,  413,
      417,  421,  423,  412,  246,  261,  285,  543,  264,  268,
      543,  543,  212,  250,  272,  300,  223,  274,  543,  410,

      397,  396,    0,  392,    0,    0,  377,  383,  372,  379,
        0,    0,  373,  369,    0,  373,    0,  368,  368,  367,
      364,  376,  366,  370,  375,  374,  372,  360,  365,    0,
      351,  363,  304,  310,  319,  255,  327,  265,  543,  330,
      333,  375,  355,    0,  354,  355,    0,    0,  350,  351,
      356,  344,    0,  350,  336,  342,  333,    0,  341,  337,
      335,  319,  324,  319,    0,  310,  311,    0,  336,  341,
      358,  350,  364,  543,  543,  310,  288,  275,  271,    0,
        0,    0,  278,  272,    0,    0,    0,    0,    0,    0,
      263,  247,  225,  543,  372,  382,  543,  211,  203,  187,

        0,  170,  166,    0,  177,  149,  543,    0,  104,    0,
        0,    0,    0,    0,   76,    0,  543,  435,  442,  445,
      452,  456,  116,  457
    } ;

static const flex_int16_t yy_def[325] =
    {   0,
      317,    1,  317,  317,  317,  317,  317,  318,  317,  317,
      317,  319,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  320,  320,
      317,  317,  317,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  317,
      317,  317,  317,  317,  318,  317,  318,  317,  317,  317,
      317,  319,  319,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  321,  317,  317,  317,  317,  317,  317,  317,
      322,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  320,  318,  319,  317,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  317,  317,  317,  317,
      317,  317,  321,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  323,  322,  317,  317,  317,  317,  317,  317,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  317,  317,  317,  317,  317,  317,
      317,  317,  323,  324,  317,  317,  317,  317,  317,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  317,  317,  317,  324,  317,  317,  317,  317,
      317,  317,  317,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  317,  317,
      317,  317,  317,  317,  317,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  317,  317,  317,  317,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  317,  320,  320,  320,
      320,  320,  320,  320,  320,  320,    0,  317,  317,  317,
      317,  317,  317,  317
    } ;

static const flex_int16_t yy_nxt[614] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   29,   30,   29,   29,   29,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   29,
       42,   29,   43,   29,   29,   29,   29,   44,   45,   46,
       47,   48,   49,   29,   29,   29,   50,   51,   52,   53,
       56,   58,   59,   60,   65,  107,   70,   67,   71,   71,
       71,   93,   94,   72,  108,   66,   68,   69,   73,   61,
       96,  127,   99,  100,   97,   74,   75,  101,   83,   83,

       83,   88,  129,  112,   57,   75,  113,   76,   76,   77,
       78,  109,   56,  110,   84,   89,   85,   90,   91,   78,
      193,  104,  111,   79,  115,   80,   81,   78,  105,  207,
      208,  116,   63,   86,  106,  128,   78,  140,  119,  120,
      316,   85,   82,   71,   71,   71,   57,  139,  121,  140,
       80,  122,  141,   81,  139,  131,  132,   56,  147,  132,
      167,  315,  140,  134,  134,  134,   75,  168,   76,   76,
       77,  142,  131,  132,  140,  135,  136,  148,  132,  136,
       78,  145,  180,  146,   79,   75,   80,   77,   77,   77,
      181,   57,  135,  136,  182,  314,  183,   78,  136,   78,

      137,  146,  137,   82,  174,  138,  138,  138,  146,  170,
       75,   80,   83,   83,   83,  140,   78,  176,  145,  171,
      172,  175,  313,  146,   78,  312,  146,  311,   84,  185,
       85,  185,  177,  310,  186,  186,  186,  134,  134,  134,
      140,   78,  138,  138,  138,  309,  235,   86,  146,  187,
      188,  194,  189,  188,  189,   85,  242,  190,  190,  190,
      138,  138,  138,  186,  186,  186,  187,  188,  235,  195,
      196,  197,  188,  191,  308,  243,  191,  306,  186,  186,
      186,  190,  190,  190,  237,  190,  190,  190,  198,  271,
      191,  132,  196,  305,  132,  191,  197,  233,  136,  233,

      239,  136,  234,  234,  234,  238,  237,  239,  132,  239,
      304,  271,  240,  132,  240,  136,  303,  241,  241,  241,
      136,  234,  234,  234,  302,  239,  238,  234,  234,  234,
      301,  269,  239,  269,  239,  300,  270,  270,  270,  272,
      188,  272,  299,  188,  273,  273,  273,  241,  241,  241,
      241,  241,  241,  270,  270,  270,  298,  188,  270,  270,
      270,  293,  188,  274,  292,  291,  274,  273,  273,  273,
      295,  294,  295,  290,  294,  296,  296,  296,  289,  288,
      274,  273,  273,  273,  287,  274,  286,  285,  294,  296,
      296,  296,  284,  294,  297,  283,  282,  297,  281,  296,

      296,  296,  280,  279,  278,  277,  276,  275,  275,  268,
      267,  297,  307,  266,  265,  307,  297,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  307,
      252,  251,  250,  249,  307,   55,  248,   55,   55,   55,
       55,   55,   62,  247,  246,   62,   62,   62,   62,   95,
       95,   95,  133,  245,  133,  133,  133,  133,  133,  144,
      144,  236,  244,  236,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  206,  205,
      204,  203,  202,  201,  200,  199,  199,  192,  192,  184,

      179,  178,  173,  169,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
       63,  150,  149,  143,  130,   62,  126,  125,  124,  123,
      118,  117,  114,  103,  102,   98,   92,   87,   64,   63,
       54,  317,    3,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317
    } ;

static const flex_int16_t yy_chk[614] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   10,   10,   11,   16,   38,   19,   18,   19,   19,
       19,   27,   27,   20,   38,   16,   18,   18,   20,   11,
       30,   51,   34,   34,   30,   20,   22,   34,   22,   22,

       22,   25,   62,   40,    8,   21,   40,   21,   21,   21,
       22,   39,   55,   39,   22,   25,   22,   25,   25,   21,
      323,   37,   39,   21,   42,   21,   21,   22,   37,  158,
      158,   42,   62,   22,   37,   51,   21,   82,   45,   45,
      315,   22,   21,   71,   71,   71,   55,   79,   45,   79,
       21,   45,   80,   21,   82,   71,   71,   96,   85,   71,
      116,  309,   82,   75,   75,   75,   76,  116,   76,   76,
       76,   80,   71,   71,   79,   75,   75,   85,   71,   75,
       76,   84,  124,   84,   76,   77,   76,   77,   77,   77,
      124,   96,   75,   75,  125,  306,  125,   76,   75,   77,

       78,   86,   78,   76,  120,   78,   78,   78,   84,  118,
       83,   76,   83,   83,   83,  139,   77,  121,   86,  118,
      118,  120,  305,  145,   83,  303,   86,  302,   83,  131,
       83,  131,  121,  300,  131,  131,  131,  134,  134,  134,
      139,   83,  137,  137,  137,  299,  193,   83,  145,  134,
      134,  144,  135,  134,  135,   83,  197,  135,  135,  135,
      138,  138,  138,  185,  185,  185,  134,  134,  193,  144,
      144,  144,  134,  138,  298,  197,  138,  293,  186,  186,
      186,  189,  189,  189,  194,  190,  190,  190,  144,  236,
      138,  186,  144,  292,  186,  138,  144,  187,  190,  187,

      238,  190,  187,  187,  187,  195,  194,  195,  186,  198,
      291,  236,  196,  186,  196,  190,  284,  196,  196,  196,
      190,  233,  233,  233,  283,  238,  198,  234,  234,  234,
      279,  235,  195,  235,  198,  278,  235,  235,  235,  237,
      234,  237,  277,  234,  237,  237,  237,  240,  240,  240,
      241,  241,  241,  269,  269,  269,  276,  234,  270,  270,
      270,  267,  234,  241,  266,  264,  241,  272,  272,  272,
      271,  270,  271,  263,  270,  271,  271,  271,  262,  261,
      241,  273,  273,  273,  260,  241,  259,  257,  270,  295,
      295,  295,  256,  270,  273,  255,  254,  273,  252,  296,

      296,  296,  251,  250,  249,  246,  245,  243,  242,  232,
      231,  273,  296,  229,  228,  296,  273,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  216,  214,  296,
      213,  210,  209,  208,  296,  318,  207,  318,  318,  318,
      318,  318,  319,  204,  202,  319,  319,  319,  319,  320,
      320,  320,  321,  201,  321,  321,  321,  321,  321,  322,
      322,  324,  200,  324,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      167,  166,  164,  163,  162,  161,  160,  159,  157,  156,
      155,  154,  153,  152,  151,  148,  147,  142,  141,  126,

      123,  122,  119,  117,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       97,   94,   90,   81,   70,   63,   49,   48,   47,   46,
       44,   43,   41,   36,   35,   33,   26,   23,   15,   12,
        7,    3,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C99-scanner.lex"
#line 10 "C99-scanner.lex"
#include<bits/stdc++.h>
#include "SymbolTable.h"
#include "writer.h"
#include <stdio.h>
#include <cstring>
#include <fstream>
#include "y.tab.hh"

extern ofstream output;
extern void parseOpenMP(const char* _input, void * _exprParse(const char*));
extern void yyerror(const char *);
extern void MPIEmpezarSecuencial();
extern string construirReductionDist(int it);
extern string construirAllReductionDist(int it);
extern void ReducirReduceConstVariables();
extern void lastLine();

static void count(void);
static void comment(void);
static char * get_pragma();
// static int check_type(void);

extern ofstream logFile;
extern ofstream errFile;
extern SymbolTable table;

int column = 0;
int line_count = 1;
int conArgc = 0;
int conArgv = 0;

extern int n_llaves;
extern int enCluster;
extern string guardarLineasDist;
extern int dist_n_llaves;
extern int enFor;
extern int MPIInitDone;
extern std::vector<const char *> argsReduceOpsDistribute;
extern std::vector<const char *> argsAllReduceOpsDistribute;
extern std::vector<std::string> varsReduceConstruir;
extern std::vector<std::vector<std::string>> reduceConst;
extern char *linea;
extern int enFuncion;

using namespace std;

extern YYSTYPE yylval;

extern int error_count;

#line 737 "lex.yy.cc"
#line 738 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 64 "C99-scanner.lex"

#line 955 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 318 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 543 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 65 "C99-scanner.lex"
{
                char * line = get_pragma();
                char * pragma = strstr(line, "pragma");
                if (pragma != NULL) {
                    parseOpenMP(pragma+7, NULL);
					char *red;
					char *busqueda = line;
					string newRed;

					if (strstr(line, "cluster") == NULL && (!enCluster || strstr(line, "distribute") == NULL)) {
						if (enDistribute && enFor == 0) {
							guardarLineasDist += '#';
							guardarLineasDist += line;

							if ((strstr(line, "for") != NULL || strstr(line, "simd") != NULL)) {
								if (enReductionDistribute) {
									while ((red = strstr(busqueda, "reduction")) != NULL) {
										newRed = "";
										busqueda = red + 10;
										while (*busqueda != ')') {
											newRed += *busqueda;
											busqueda++;
										}
										varsReduceConstruir.push_back(newRed);
									}
									ReducirReduceConstVariables();
									varsReduceConstruir.clear();
									for (long unsigned int i = 0; i < argsReduceOpsDistribute.size(); i++) {
										guardarLineasDist += construirReductionDist(i);
									}
								}
								if (enAllReductionDistribute) {
									while ((red = strstr(busqueda, "reduction")) != NULL) {
										newRed = "";
										busqueda = red + 10;
										while (*busqueda != ')') {
											newRed += *busqueda;
											busqueda++;
										}
										varsReduceConstruir.push_back(newRed);
									}
									ReducirReduceConstVariables();
									varsReduceConstruir.clear();
									for (long unsigned int i = 0; i < argsAllReduceOpsDistribute.size(); i++) {
										guardarLineasDist += construirAllReductionDist(i);
									}
								}

								reduceConst.clear();
							}

							guardarLineasDist += '\n';
						}
						else {
							output << "	#" << line;

							if ((strstr(line, "for") != NULL || strstr(line, "simd") != NULL)) {
								if (enReductionDistribute) {
									while ((red = strstr(busqueda, "reduction")) != NULL) {
										newRed = "";
										busqueda = red + 10;
										while (*busqueda != ')') {
											newRed += *busqueda;
											busqueda++;
										}
										varsReduceConstruir.push_back(newRed);
									}
									ReducirReduceConstVariables();
									varsReduceConstruir.clear();
									for (long unsigned int i = 0; i < argsReduceOpsDistribute.size(); i++) {
										output << construirReductionDist(i);
									}
								}
								if (enAllReductionDistribute) {
									while ((red = strstr(busqueda, "reduction")) != NULL) {
										newRed = "";
										busqueda = red + 10;
										while (*busqueda != ')') {
											newRed += *busqueda;
											busqueda++;
										}
										varsReduceConstruir.push_back(newRed);
									}
									ReducirReduceConstVariables();
									varsReduceConstruir.clear();
									for (long unsigned int i = 0; i < argsAllReduceOpsDistribute.size(); i++) {
										output << construirAllReductionDist(i);
									}
								}

								reduceConst.clear();
							}

							output << endl;
						}
					}
				}
				else{
					output << "#" << line << endl;
				}
              }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 166 "C99-scanner.lex"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 167 "C99-scanner.lex"
{ /* consume //-comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 170 "C99-scanner.lex"
{ count(); return(AUTO); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 171 "C99-scanner.lex"
{ count(); return(BOOL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 172 "C99-scanner.lex"
{ count(); return(BREAK); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 173 "C99-scanner.lex"
{ count(); return(CASE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 174 "C99-scanner.lex"
{ count(); return(CHAR); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 175 "C99-scanner.lex"
{ count(); return(COMPLEX); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 176 "C99-scanner.lex"
{ count(); return(CONST); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 177 "C99-scanner.lex"
{ count(); return(CONTINUE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 178 "C99-scanner.lex"
{ count(); return(DEFAULT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 179 "C99-scanner.lex"
{ count(); return(DO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 180 "C99-scanner.lex"
{ count(); return(DOUBLE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 181 "C99-scanner.lex"
{ count(); return(ELSE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 182 "C99-scanner.lex"
{ count(); return(ENUM); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 183 "C99-scanner.lex"
{ count(); return(EXTERN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 184 "C99-scanner.lex"
{ count(); return(FLOAT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 185 "C99-scanner.lex"
{ count(); return(FOR); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 186 "C99-scanner.lex"
{ count(); return(GOTO); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 187 "C99-scanner.lex"
{ count(); return(IF); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 188 "C99-scanner.lex"
{ count(); return(IMAGINARY); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 189 "C99-scanner.lex"
{ count(); return(INLINE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 190 "C99-scanner.lex"
{ count(); return(INT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 191 "C99-scanner.lex"
{ count(); return(LONG); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 192 "C99-scanner.lex"
{ count(); return(REGISTER); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 193 "C99-scanner.lex"
{ count(); return(RESTRICT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 194 "C99-scanner.lex"
{ count(); return(RETURN); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 195 "C99-scanner.lex"
{ count(); return(SHORT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 196 "C99-scanner.lex"
{ count(); return(SIGNED); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 197 "C99-scanner.lex"
{ count(); return(SIZEOF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 198 "C99-scanner.lex"
{ count(); return(STATIC); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 199 "C99-scanner.lex"
{ count(); return(STRUCT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 200 "C99-scanner.lex"
{ count(); return(SWITCH); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 201 "C99-scanner.lex"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 202 "C99-scanner.lex"
{ count(); return(UNION); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 203 "C99-scanner.lex"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 204 "C99-scanner.lex"
{ count(); return(VOID); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 205 "C99-scanner.lex"
{ count(); return(VOLATILE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 206 "C99-scanner.lex"
{ count(); return(WHILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 208 "C99-scanner.lex"
{
	logFile << "LEYENDO: " << yytext << endl;
	count();
	SymbolInfo *s = table.getSymbolInfo(yytext);
	if(s != NULL && s->getSymIsType()){
		if (strcmp(yytext, "FILE") == 0) {
			fprintf(stderr, "FILE en USER_DEFINED\n");
		}
		yylval.sym = new SymbolInfo(yytext, (char *) yytext);
		return USER_DEFINED;
	}
	else if (s != NULL) {
		if (strcmp(yytext, "FILE") == 0) {
			fprintf(stderr, "FILE en IDENTIFIER\n");
		}
		yylval.sym = s;
		return IDENTIFIER;
	}
	else {
		if (strcmp(yytext, "FILE") == 0) {
			fprintf(stderr, "FILE en IDENTIFIER\n");
		}
		SymbolInfo *s = new SymbolInfo(yytext, (char *)"IDENTIFIER");
		yylval.sym = s;
		if (!MPIInitDone) {
			if (strcmp(yytext, "argc") == 0) {
				conArgc = 1;
			}
			if (strcmp(yytext, "argv") == 0) {
				conArgv = 1;
			}
		}

		return IDENTIFIER;
	}
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 245 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 246 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 247 "C99-scanner.lex"
{ 
	count();
	SymbolInfo *s = new SymbolInfo(yytext, (char *)"CONSTANT");
	yylval.sym = s;
	return(CONSTANT); 
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 253 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 255 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 256 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 257 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 258 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 259 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 260 "C99-scanner.lex"
{ count(); return(CONSTANT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 263 "C99-scanner.lex"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 265 "C99-scanner.lex"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 266 "C99-scanner.lex"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 267 "C99-scanner.lex"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 268 "C99-scanner.lex"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 269 "C99-scanner.lex"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 270 "C99-scanner.lex"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 271 "C99-scanner.lex"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 272 "C99-scanner.lex"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 273 "C99-scanner.lex"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 274 "C99-scanner.lex"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 275 "C99-scanner.lex"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 276 "C99-scanner.lex"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 277 "C99-scanner.lex"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 278 "C99-scanner.lex"
{ count(); return(INC_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 279 "C99-scanner.lex"
{ count(); return(DEC_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 280 "C99-scanner.lex"
{ count(); return(PTR_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 281 "C99-scanner.lex"
{ count(); return(AND_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 282 "C99-scanner.lex"
{ count(); return(OR_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 283 "C99-scanner.lex"
{ count(); return(LE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 284 "C99-scanner.lex"
{ count(); return(GE_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 285 "C99-scanner.lex"
{ count(); return(EQ_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 286 "C99-scanner.lex"
{ count(); return(NE_OP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 287 "C99-scanner.lex"
{ count(); return(';'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 288 "C99-scanner.lex"
{ count(); if (enCluster) {if (n_llaves == -100) {n_llaves = 0;} n_llaves++;} if (enDistribute) {dist_n_llaves++;} return('{'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 289 "C99-scanner.lex"
{ count(); if (enCluster) {n_llaves--; if (n_llaves < 0) {exit(200);} else if(n_llaves == 0) {n_llaves = -100;}}
					if (enDistribute) {dist_n_llaves--; if (dist_n_llaves < 0) {exit(201);} else if (dist_n_llaves == 0) {dist_n_llaves = -100;}} 
					return('}'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 292 "C99-scanner.lex"
{ count(); return(','); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 293 "C99-scanner.lex"
{ count(); return(':'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 294 "C99-scanner.lex"
{ count(); return('='); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 295 "C99-scanner.lex"
{ count(); return('('); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 296 "C99-scanner.lex"
{ count(); return(')'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 297 "C99-scanner.lex"
{ count(); return('['); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 298 "C99-scanner.lex"
{ count(); return(']'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 299 "C99-scanner.lex"
{ count(); return('.'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 300 "C99-scanner.lex"
{ count(); return('&'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 301 "C99-scanner.lex"
{ count(); return('!'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 302 "C99-scanner.lex"
{ count(); return('~'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 303 "C99-scanner.lex"
{ count(); return('-'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 304 "C99-scanner.lex"
{ count(); return('+'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 305 "C99-scanner.lex"
{ count(); return('*'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 306 "C99-scanner.lex"
{ count(); return('/'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 307 "C99-scanner.lex"
{ count(); return('%'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 308 "C99-scanner.lex"
{ count(); return('<'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 309 "C99-scanner.lex"
{ count(); return('>'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 310 "C99-scanner.lex"
{ count(); return('^'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 311 "C99-scanner.lex"
{ count(); return('|'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 312 "C99-scanner.lex"
{ count(); return('?'); }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 314 "C99-scanner.lex"
{ count(); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 315 "C99-scanner.lex"
{ /* Add code to complain about unmatched characters */ }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 317 "C99-scanner.lex"
ECHO;
	YY_BREAK
#line 1660 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 318 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 318 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 317);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 317 "C99-scanner.lex"


int yywrap(void)
{
	lastLine();
	
	if (MPIInitDone) {
		output << endl << DeclareTypes << "}";
	}

	return 1;
}


char * get_pragma(void)
{
        char c;
        char * line = (char *) malloc(512);
        int i=0;

        ECHO;

        while ((c = yyinput()) != 0 && (c != '\n' && c != '\r'))   /* (EOF maps to 0) */
        {
                if (yyout != NULL)
                        fputc(c, yyout);
                line[i++] = c;
        }
        if (yyout != NULL)
                fputc(c, yyout);
        line[i] = 0;
        return(line);
}

void comment(void)
{
	char c, prev = 0;

        ECHO;
  
	while ((c = yyinput()) != 0)      /* (EOF maps to 0) */
	{
		if (yyout != NULL)
			fputc(c, yyout);
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	yyerror("unterminated comment");
}

void count(void)
{
	int i;
	setYytext(yytext);
	updateText();
	
	for (i = 0; yytext[i] != '\0'; i++) {
		if (yytext[i] == '\n'){
			line_count++;
			column = 0;
		}
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;
	}

	//ECHO;
}


/* int check_type(void)
{ */
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return TYPE_NAME;
*
*	return IDENTIFIER;
*/

/*
*	it actually will only return IDENTIFIER
*/

	/* return IDENTIFIER;
} */

